name: health
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.7
  intl: ^0.19.0
  fluttertoast: ^8.2.2
  flutter_local_notifications: ^17.1.2
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  firebase_analytics: ^10.4.3
  permission_handler: ^11.3.1
  timezone: ^0.9.3
  firebase_auth: ^4.19.6
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  cloud_firestore: ^4.9.0  # Добавьте эту строку для cloud_firestore

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/icons/
     - assets/images/
